# Generated by Django 5.2.4 on 2025-07-25 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0002_formdata_delete_dynamicformdata'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FormData',
            new_name='DynamicFormData',
        ),
    ]
